package com.ximai.savingsmore.save.modle;

import java.io.Serializable;
import java.util.List;

/**
 * Created by caojian on 16/11/24.
 */
public class GoodDetial  implements Serializable{
//    public Brand Brand;
//    public City City;
//    public Currency Currency;
//    public FirstClass FirstClass;
//    public Invoice Invoice;
//    public SecondClass SecondClass;
//    public UnitClass Unit;
//    public User User;
//    public String StartTimeName;
//    public String EndTimeName;
//    public String OriginalPrice;
//    public String Price;
//    public String PromotionTypeName;
//    public String Distance;
//    public List<Images> Images;
//    public String Name;
//    public String PromotionCause;
//    public String Address;
//    public String Preferential;
//    public String Introduction;
//    public String Description;
//    public String CommentCount;
//    public String Score;
//------------------------------------------------------------------------
    public Area Area;
//     private List<ChainStores> ChainStores ;
    public String CreateDateName;
    public City City;
    public Country Country;
    public Currency Currency;
    public User User;
    //    public Brand Brand;
    public String HitCount;
    public String AreaId;
    public String OriginalPrice;
    public String ProvinceId;
    public List<Images> Images ;
    public List<ChainStores> ChainStores ;
    public String PromotionType;
    public String PurchaseQuantity;
    public PromotionCause PromotionCause;
    public String CreateTimeName;
    public String Score;
    public String UnitId;
    public String Number;
    public String Distance;
    public Invoice Invoice;
    public String FavouriteCount;
    public String SecondClassId;
    public String Preferential;
    public String EndTimeName;
    public String Price;
    public String IsDeleted;
    public String Id;
    public String Longitude;
    public SecondClass SecondClass;
    public String IsProcurementService;
    public String IsEnabled;
    public String CityId;
    public String SharedCount;
    public String CurrencyId;
    public boolean IsTop;
    public boolean IsFavourite;
    public String Rebate;
    public String IsShared;
    public Unit Unit;
    public String Introduction;
    public String PreferentialPrice;
    public String Image;
    public String Latitude;
    public String FirstClassId;
    public String StartTime;
    public String ImagesJson;
    public String CommentCount;
    public String SaleCount;
    public String Description;
    public String ChainStoresJson;
    public String StartTimeName;
    public Province Province;
    public String Brand;
    public String Name;
    public String FreeQuantity;
    public String CreateTime;
    public String Address;
    public String InvoiceId;
    public String EndTime;
    public String VideoId;
    public String VideoPath;
    public String PromotionTypeName;
    public FirstClass FirstClass;
    public DeliveryService DeliveryService;//送货服务
    public Premium Premium;//送货保险
    public String StoreCount;

//        public String Area;
//        public List<String> ChainStores;
//        public City City;
//        public Currency Currency;
//        public DeliveryService DeliveryService;
//        public FirstClass FirstClass;
//        public Invoice Invoice;
//        public Premium Premium;
//        public PromotionCause PromotionCause;
//        public Province Province;
//        public SecondClass SecondClass;
//        public Unit Unit;
//        public User User;
//        public String StartTimeName;
//        public String EndTimeName;
//        public String PromotionTypeName;
//        public String Distance;
//        public boolean IsFavourite;
//        public boolean IsShared;
//        public List<Images> Images;
//        public String ImagesJson;
//        public String ChainStoresJson;
//        public boolean IsExpire;
//        public String Name;
//        public String Number;
//        public String Image;
//        public String PromotionCauseId;
//        public String FirstClassId;
//        public String SecondClassId;
//        public String ProvinceId;
//        public String CityId;
//        public String AreaId;
//        public String Address;
//        public String Brand;
//        public String StartTime;
//        public String EndTime;
//        public String OriginalPrice;
//        public String Price;
//        public String CurrencyId;
//        public String UnitId;
//        public String ProductType;
//        public String PromotionType;
//        public String PurchaseQuantity;
//        public String FreeQuantity;
//        public String PreferentialPrice;
//        public String Preferential;
//        public String Rebate;
//        public String InvoiceId;
//        public boolean IsProcurementService;
//        public String Introduction;
//        public String Description;
//        public String HitCount;
//        public String SharedCount;
//        public String FavouriteCount;
//        public String CommentCount;
//        public String SaleCount;
//        public String SalePrice;
//        public boolean IsEnabled;
//        public boolean IsDeleted;
//        public boolean IsTop;
//        public String Longitude;
//        public String Latitude;
//        public String Score;
        public String DeliveryServiceId;
        public String PremiumId;
//        public String Id;
//        public String CreateTime;
//        public String CreateTimeName;
//        public String CreateDateName;
}